# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 03:55
from __future__ import unicode_literals

import ckeditor.fields
import colorful.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='astronauta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('texto', ckeditor.fields.RichTextField(verbose_name='Texto')),
                ('tipo', models.CharField(choices=[('apollo', 'Apollo'), ('gemini', 'Gemini'), ('mercury', 'Mercury')], default='apollo', max_length=9)),
                ('photo', models.ImageField(upload_to='sitio/images/astronautas', verbose_name='Foto')),
            ],
            options={
                'verbose_name': '5 - Astronauta',
                'verbose_name_plural': '5 - Astronautas',
            },
        ),
        migrations.CreateModel(
            name='indicador',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('percent', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(100)])),
                ('color', colorful.fields.RGBColorField()),
            ],
            options={
                'verbose_name': '4 - Andamento da Missão: Indicador',
                'verbose_name_plural': '4 - Andamento da Missão: Indicadores',
            },
        ),
        migrations.CreateModel(
            name='initmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '1 - Mensagem Inicial',
                'verbose_name_plural': '1 - Mensagens Iniciais',
            },
        ),
        migrations.CreateModel(
            name='mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '3 - Andamento da Missão: Texto',
                'verbose_name_plural': '3 - Andamento da Missão: Texto',
            },
        ),
        migrations.CreateModel(
            name='portfc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', ckeditor.fields.RichTextField(verbose_name='Nome & Descrição da Empresa')),
                ('logo', models.ImageField(upload_to='sitio/images/portifolio', verbose_name='Logo')),
            ],
            options={
                'verbose_name': '6 - Portifólio - Em Construção',
                'verbose_name_plural': '6 - Portifólio - Em Construção',
            },
        ),
        migrations.CreateModel(
            name='portfcl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', ckeditor.fields.RichTextField(verbose_name='Nome & Descrição da Empresa')),
                ('logo', models.ImageField(upload_to='sitio/images/portifolio', verbose_name='Logo')),
                ('andament', models.CharField(choices=[('const', 'Em Construção'), ('lanc', 'Lançados')], default='const', max_length=9)),
            ],
            options={
                'verbose_name': '8 - Portifólio (Em Desenvolvimento)',
                'verbose_name_plural': '8 - Portifólio (Em Desenvolvimento)',
            },
        ),
        migrations.CreateModel(
            name='portfl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', ckeditor.fields.RichTextField(verbose_name='Nome & Descrição da Empresa')),
                ('logo', models.ImageField(upload_to='sitio/images/portifolio', verbose_name='Logo')),
            ],
            options={
                'verbose_name': '7 - Portifólio - Lançado',
                'verbose_name_plural': '7 - Portifólio - Lançados',
            },
        ),
        migrations.CreateModel(
            name='valore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Missões')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
            ],
            options={
                'verbose_name': '2 - Conquista da Empresa',
                'verbose_name_plural': '2 - Conquistas da Empresa',
            },
        ),
    ]
