# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_auto_20170503_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': '3 - Texto do Site', 'verbose_name_plural': '3 - Textos do Site'},
        ),
        migrations.AlterField(
            model_name='mission',
            name='tipo',
            field=models.CharField(choices=[('ski', 'Astronautas'), ('mis', 'Missão'), ('por', 'Portifólio')], default='ski', max_length=3),
        ),
    ]
