# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_auto_20170614_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='percent',
            field=models.CharField(max_length=3, verbose_name='Meta'),
        ),
    ]
