# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_auto_20170614_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='percent',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Percent'),
        ),
    ]
