# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0013_remove_indicador_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='atual2',
            field=models.PositiveIntegerField(max_length=3, verbose_name='Atual'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='meta2',
            field=models.PositiveIntegerField(max_length=3, verbose_name='Meta'),
        ),
    ]
