# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='initmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.TextField(verbose_name='Mensagem de Início')),
            ],
        ),
    ]
