# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronauta',
            name='texto',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='initmes',
            name='descript',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='portfc',
            name='descript',
            field=models.TextField(verbose_name='Nome & Descrição da Empresa'),
        ),
        migrations.AlterField(
            model_name='portfcl',
            name='descript',
            field=models.TextField(verbose_name='Nome & Descrição da Empresa'),
        ),
        migrations.AlterField(
            model_name='portfl',
            name='descript',
            field=models.TextField(verbose_name='Nome & Descrição da Empresa'),
        ),
    ]
