# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='valore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(verbose_name='Missões')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
            ],
        ),
        migrations.RemoveField(
            model_name='mission',
            name='item',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='valor',
        ),
    ]
