# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_auto_20170426_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='apollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('text', models.TextField(verbose_name='Texto')),
                ('photo', models.ImageField(upload_to='sitio/images/apollo', verbose_name='Foto')),
            ],
        ),
    ]
