# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_mission_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='tipo',
            field=models.CharField(choices=[('skills', 'Missao'), ('team', 'Astronautas'), ('portfolio', 'Portfolio')], default='skills', max_length=9),
        ),
    ]
