# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_apollo'),
    ]

    operations = [
        migrations.CreateModel(
            name='gemini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('text', models.TextField(verbose_name='Texto')),
                ('photo', models.ImageField(upload_to='sitio/images/astronautas', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='mercury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('text', models.TextField(verbose_name='Texto')),
                ('photo', models.ImageField(upload_to='sitio/images/astronautas', verbose_name='Foto')),
            ],
        ),
        migrations.AlterField(
            model_name='apollo',
            name='photo',
            field=models.ImageField(upload_to='sitio/images/astronautas', verbose_name='Foto'),
        ),
    ]
