# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_auto_20170426_0218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apollo',
            options={'verbose_name': 'Astronauta Apollo', 'verbose_name_plural': 'Astronautas Apollo'},
        ),
        migrations.AlterModelOptions(
            name='gemini',
            options={'verbose_name': 'Astronauta Gemini', 'verbose_name_plural': 'Astronautas Gemini'},
        ),
        migrations.AlterModelOptions(
            name='initmes',
            options={'verbose_name': 'Mensagem Inicial', 'verbose_name_plural': 'Mensagem Inicial'},
        ),
        migrations.AlterModelOptions(
            name='mercury',
            options={'verbose_name': 'Astronauta Mercury', 'verbose_name_plural': 'Astronautas Mercury'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Missão da Empresa', 'verbose_name_plural': 'Missões da Empresa'},
        ),
        migrations.AlterModelOptions(
            name='valore',
            options={'verbose_name': 'Conquista da Empresa', 'verbose_name_plural': 'Conquistas da Empresa'},
        ),
    ]
