# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_auto_20170426_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.TextField(verbose_name='Nome & Descrição da Empresa')),
                ('logo', models.ImageField(upload_to='sitio/images/portifolio', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Portifólio - Em Construção',
                'verbose_name_plural': 'Portifólio - Em Construção',
            },
        ),
        migrations.CreateModel(
            name='portfl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.TextField(verbose_name='Nome & Descrição da Empresa')),
                ('logo', models.ImageField(upload_to='sitio/images/portifolio', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Portifólio - Lançado',
                'verbose_name_plural': 'Portifólio - Lançados',
            },
        ),
        migrations.AlterModelOptions(
            name='initmes',
            options={'verbose_name': 'Mensagem Inicial', 'verbose_name_plural': 'Mensagens Iniciais'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Texto: Andamento da Missão', 'verbose_name_plural': 'Texto: Andamento da Missão'},
        ),
    ]
