# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_auto_20170503_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='indicador',
        ),
    ]
