# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:33
from __future__ import unicode_literals

import colorful.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_delete_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('percent', models.PositiveIntegerField(primary_key=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('color', colorful.fields.RGBColorField()),
            ],
            options={
                'verbose_name': '4 - Andamento da Missão: Indicador',
                'verbose_name_plural': '4 - Andamento da Missão: Indicadores',
            },
        ),
    ]
