# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_indicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='color',
            field=models.CharField(choices=[('1', 'Azul'), ('2', 'Laranja'), ('3', 'Amarelo'), ('4', 'Marrom')], default='1', max_length=1),
        ),
    ]
