# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_indicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='atual2',
            field=models.CharField(default=django.utils.timezone.now, max_length=3, verbose_name='Atual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='meta2',
            field=models.CharField(default=django.utils.timezone.now, max_length=3, verbose_name='Meta'),
            preserve_default=False,
        ),
    ]
