# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_indicador_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='astronauta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('text', models.TextField(verbose_name='Texto')),
                ('tipo', models.CharField(choices=[('apollo', 'Apollo'), ('gemini', 'Gemini'), ('mercury', 'Mercury')], default='apollo', max_length=1)),
                ('photo', models.ImageField(upload_to='sitio/images/astronautas', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Astronauta Mercury',
                'verbose_name_plural': 'Astronautas Mercury',
            },
        ),
    ]
