# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0012_auto_20170614_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='percent',
        ),
    ]
