# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0014_auto_20170426_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='astronauta',
            options={'verbose_name': '5 - Astronauta', 'verbose_name_plural': '5 - Astronautas'},
        ),
        migrations.AlterModelOptions(
            name='indicador',
            options={'verbose_name': '4 - Andamento da Missão: Indicador', 'verbose_name_plural': '4 - Andamento da Missão: indicadores'},
        ),
        migrations.AlterModelOptions(
            name='initmes',
            options={'verbose_name': '1 - Mensagem Inicial', 'verbose_name_plural': '1 - Mensagens Iniciais'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': '3 - Andamento da Missão: Texto', 'verbose_name_plural': '3 - Andamento da Missão: Texto'},
        ),
        migrations.AlterModelOptions(
            name='portfc',
            options={'verbose_name': '6 - Portifólio - Em Construção', 'verbose_name_plural': '6 - Portifólio - Em Construção'},
        ),
        migrations.AlterModelOptions(
            name='portfcl',
            options={'verbose_name': '8 - Portifólio', 'verbose_name_plural': '8 - Portifólio'},
        ),
        migrations.AlterModelOptions(
            name='portfl',
            options={'verbose_name': '7 - Portifólio - Lançado', 'verbose_name_plural': '7 - Portifólio - Lançados'},
        ),
        migrations.AlterModelOptions(
            name='valore',
            options={'verbose_name': '2 - Conquista da Empresa', 'verbose_name_plural': '2 - Conquistas da Empresa'},
        ),
        migrations.AlterField(
            model_name='portfcl',
            name='andament',
            field=models.CharField(choices=[('const', 'Em Construção'), ('lanc', 'Lançados')], default='const', max_length=9),
        ),
    ]
