# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0014_auto_20170614_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valore',
            options={'verbose_name': '2 - Meta da Missão', 'verbose_name_plural': '2 - Metas da Missão'},
        ),
    ]
