# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0015_auto_20170426_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicador',
            options={'verbose_name': '4 - Andamento da Missão: Indicador', 'verbose_name_plural': '4 - Andamento da Missão: Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='portfcl',
            options={'verbose_name': '8 - Portifólio (Em Desenvolvimento)', 'verbose_name_plural': '8 - Portifólio (Em Desenvolvimento)'},
        ),
    ]
