# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0015_auto_20170614_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='atual2',
            field=models.PositiveIntegerField(verbose_name='Atual'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='meta2',
            field=models.PositiveIntegerField(verbose_name='Meta'),
        ),
    ]
