# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 04:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0017_auto_20170426_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initmes',
            name='content',
        ),
        migrations.AlterField(
            model_name='initmes',
            name='descript',
            field=ckeditor.fields.RichTextField(verbose_name='Mensagem de Início'),
        ),
    ]
