# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 05:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0018_auto_20170427_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronauta',
            name='content',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='content',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='content',
        ),
        migrations.RemoveField(
            model_name='portfc',
            name='content',
        ),
        migrations.RemoveField(
            model_name='portfcl',
            name='content',
        ),
        migrations.RemoveField(
            model_name='portfl',
            name='content',
        ),
        migrations.RemoveField(
            model_name='valore',
            name='content',
        ),
        migrations.AlterField(
            model_name='astronauta',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='portfc',
            name='descript',
            field=ckeditor.fields.RichTextField(verbose_name='Nome & Descrição da Empresa'),
        ),
        migrations.AlterField(
            model_name='portfcl',
            name='descript',
            field=ckeditor.fields.RichTextField(verbose_name='Nome & Descrição da Empresa'),
        ),
        migrations.AlterField(
            model_name='portfl',
            name='descript',
            field=ckeditor.fields.RichTextField(verbose_name='Nome & Descrição da Empresa'),
        ),
        migrations.AlterField(
            model_name='valore',
            name='item',
            field=models.CharField(max_length=50, verbose_name='Missões'),
        ),
    ]
