# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0019_auto_20170427_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
