# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0020_auto_20170427_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astronauta',
            old_name='text',
            new_name='texto',
        ),
    ]
