# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0021_auto_20170427_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astronauta',
            old_name='texto',
            new_name='text',
        ),
    ]
