# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 02:00
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0023_auto_20170427_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='color',
            field=colorful.fields.RGBColorField(),
        ),
    ]
