# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0024_auto_20170428_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='statusport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andament', models.CharField(choices=[('const', 'Em Construção'), ('lanc', 'Lançados')], default='const', max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='portfcl',
            name='andament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.statusport'),
        ),
    ]
