# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0024_auto_20170428_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicador',
            options={},
        ),
        migrations.AlterField(
            model_name='portfl',
            name='descript',
            field=models.TextField(verbose_name='Nome & Descrição da Empresa'),
        ),
    ]
