# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0025_auto_20170429_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='choicesportf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.CharField(choices=[('Em Construção', 'Em Construção'), ('Lançadas', 'Lançadas')], default='blank', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Classes de empresas',
                'verbose_name': 'Classe de empresa',
            },
        ),
        migrations.AlterField(
            model_name='portfcl',
            name='andament',
            field=models.CharField(choices=[('Em Construção', 'Em Construção'), ('Lançadas', 'Lançadas')], default='Em Construção', max_length=20),
        ),
        migrations.DeleteModel(
            name='statusport',
        ),
    ]
