# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 07:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0025_auto_20170428_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfl',
            name='descript',
            field=ckeditor.fields.RichTextField(verbose_name='Nome & Descrição da Empresa'),
        ),
    ]
