# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0026_auto_20170428_0420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicador',
            options={'verbose_name': '4 - Andamento da Missão: Indicador', 'verbose_name_plural': '4 - Andamento da Missão: Indicadores'},
        ),
    ]
