# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0026_auto_20170430_0013'),
        ('sitio', '0027_auto_20170428_0438'),
    ]

    operations = [
    ]
