# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0028_merge_20170430_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicesportf',
            name='approval',
        ),
    ]
