# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0029_remove_choicesportf_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicesportf',
            name='approval',
            field=models.CharField(choices=[('Em Construção', 'Em Construção'), ('Lançadas', 'Lançadas')], default='blank', max_length=20),
        ),
    ]
