# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0030_choicesportf_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicesportf',
            options={'ordering': ['approval'], 'verbose_name': 'Classe de empresa', 'verbose_name_plural': 'Classes de empresas'},
        ),
    ]
