# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0031_auto_20170430_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfcl',
            options={'ordering': ['descript'], 'verbose_name': '8 - Portifólio (Em Desenvolvimento)', 'verbose_name_plural': '8 - Portifólio (Em Desenvolvimento)'},
        ),
    ]
